// focusghost/src/renderer/App.tsx
// App shell — wires IPC subscriptions, picks the active screen, renders chrome.
import React, { useEffect } from 'react';
import { useUI } from './store';
import TaskDeclaration from './screens/TaskDeclaration';
import ActiveSession from './screens/ActiveSession';
import GhostChat from './screens/GhostChat';
import Recap from './screens/Recap';
import Settings from './screens/Settings';
import History from './screens/History';
import CategoryEditor from './screens/CategoryEditor';
import CollapsedBar from './components/CollapsedBar';
import Header from './components/Header';
import { applyAccentClass } from './api';
import { SessionState } from '../shared/types';

export default function App(): JSX.Element {
  const ui = useUI();

  // Subscribe to all main-process events on mount.
  useEffect(() => {
    const offs: Array<() => void> = [];
    offs.push(window.api.onSessionState((s) => ui.setState(s)));
    offs.push(window.api.onStatsUpdate((s) => ui.setStats(s)));
    offs.push(
      window.api.onSessionRecap((r) => {
        ui.setRecap(r);
      }),
    );
    offs.push(
      window.api.onNudge((n) => {
        ui.setPendingNudge(n);
        ui.appendChat({ id: n.id, variant: 'nudge', text: n.text, timestamp: Date.now(), meta: { reason: n.reason } });
      }),
    );
    offs.push(
      window.api.onStuckActivate((p) => {
        ui.setPendingStuck(p);
        ui.setScreen('chat');
      }),
    );
    offs.push(
      window.api.onChatReply((m) => {
        ui.appendChat(m);
        ui.setChatBusy(false);
      }),
    );
    offs.push(
      window.api.onStuckResponse((m) => {
        ui.appendChat(m);
        ui.setChatBusy(false);
      }),
    );
    offs.push(window.api.onPatternNotice((p) => ui.addPattern(p)));
    offs.push(
      window.api.onSettingsChanged((s) => {
        ui.setSettings(s);
        applyAccentClass(s.accent);
      }),
    );
    offs.push(window.api.onCollapsedState((c) => ui.setCollapsed(c)));
    void window.api.getSettings().then((s) => {
      ui.setSettings(s);
      applyAccentClass(s.accent);
    });
    return () => offs.forEach((o) => o());
  }, []);

  // Auto-route based on session state.
  useEffect(() => {
    if (ui.state === SessionState.RECAP && ui.screen !== 'settings') ui.setScreen('recap');
  }, [ui.state]);

  if (ui.collapsed) return <CollapsedBar />;

  return (
    <div className="h-screen w-screen p-3" data-testid="app-root">
      <div className="shell h-full flex flex-col">
        <Header />
        <div className="flex-1 overflow-hidden">
          {ui.screen === 'task' && <TaskDeclaration />}
          {ui.screen === 'active' && <ActiveSession />}
          {ui.screen === 'chat' && <GhostChat />}
          {ui.screen === 'recap' && <Recap />}
          {ui.screen === 'settings' && <Settings />}
          {ui.screen === 'history' && <History />}
          {ui.screen === 'categories' && <CategoryEditor />}
        </div>
      </div>
    </div>
  );
}

// focusghost/src/renderer/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    screen,
    collapsed,
    settings,
    sessionState,
    recap,
    setStatsAndRisk,
    appendChat,
    addPattern,
    pendingNudge,
    pendingStuck,
    chatBusy,
  } from './stores';
  import { applyAccentClass } from './api';
  import { SessionState } from '../shared/types';
  import TaskDeclaration from './screens/TaskDeclaration.svelte';
  import ActiveSession from './screens/ActiveSession.svelte';
  import GhostChat from './screens/GhostChat.svelte';
  import Recap from './screens/Recap.svelte';
  import Settings from './screens/Settings.svelte';
  import History from './screens/History.svelte';
  import CategoryEditor from './screens/CategoryEditor.svelte';
  import CollapsedBar from './components/CollapsedBar.svelte';
  import Header from './components/Header.svelte';

  onMount(() => {
    const offs: Array<() => void> = [];
    offs.push(window.api.onSessionState((s) => sessionState.set(s)));
    offs.push(window.api.onStatsUpdate((s) => setStatsAndRisk(s)));
    offs.push(
      window.api.onSessionRecap((r) => {
        recap.set(r);
        screen.set('recap');
      }),
    );
    offs.push(
      window.api.onNudge((n) => {
        pendingNudge.set(n);
        appendChat({
          id: n.id,
          variant: 'nudge',
          text: n.text,
          timestamp: Date.now(),
          meta: { reason: n.reason },
        });
      }),
    );
    offs.push(
      window.api.onStuckActivate((p) => {
        pendingStuck.set(p);
        screen.set('chat');
      }),
    );
    offs.push(
      window.api.onChatReply((m) => {
        appendChat(m);
        chatBusy.set(false);
      }),
    );
    offs.push(
      window.api.onStuckResponse((m) => {
        appendChat(m);
        chatBusy.set(false);
      }),
    );
    offs.push(window.api.onPatternNotice((p) => addPattern(p)));
    offs.push(
      window.api.onSettingsChanged((s) => {
        settings.set(s);
        applyAccentClass(s.accent);
      }),
    );
    offs.push(window.api.onCollapsedState((c) => collapsed.set(c)));

    void window.api.getSettings().then((s) => {
      settings.set(s);
      applyAccentClass(s.accent);
    });

    return () => offs.forEach((o) => o());
  });

  // Auto-route on RECAP transition only (not on every screen change).
  let lastSeenState: SessionState = SessionState.IDLE;
  $effect(() => {
    if ($sessionState !== lastSeenState) {
      if ($sessionState === SessionState.RECAP) {
        screen.set('recap');
      }
      lastSeenState = $sessionState;
    }
  });
</script>

{#if $collapsed}
  <CollapsedBar />
{:else}
  <div class="h-screen w-screen p-3" data-testid="app-root">
    <div class="shell h-full flex flex-col">
      <Header />
      <div class="flex-1 overflow-hidden">
        {#if $screen === 'task'}
          <TaskDeclaration />
        {:else if $screen === 'active'}
          <ActiveSession />
        {:else if $screen === 'chat'}
          <GhostChat />
        {:else if $screen === 'recap'}
          <Recap />
        {:else if $screen === 'settings'}
          <Settings />
        {:else if $screen === 'history'}
          <History />
        {:else if $screen === 'categories'}
          <CategoryEditor />
        {/if}
      </div>
    </div>
  </div>
{/if}
